package org.nearbyshops.DAOs.DAOCartOrder;



import org.nearbyshops.Model.Cart;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import javax.sql.DataSource;
import java.sql.*;


@Component
public class CartService {


	@Autowired
	DataSource dataSource;



	public int saveCart(Cart cart)
	{

		Connection connection = null;
		PreparedStatement statement = null;
		int rowIdOfInsertedRow = -1;

		String insertItemCategory = "INSERT INTO "
				+ Cart.TABLE_NAME
				+ "("  
				+ Cart.SHOP_ID + ","
				+ Cart.END_USER_ID + ""
				+ " ) VALUES ( ?,?)";

//		+ "" + cart.getShopID()	+ ","
//				+ "" + cart.getEndUserID() + ""


		try {
			
			connection = dataSource.getConnection();
			statement = connection.prepareStatement(insertItemCategory,Statement.RETURN_GENERATED_KEYS);

			statement.setObject(1,cart.getShopID());
			statement.setObject(2,cart.getEndUserID());
			
			rowIdOfInsertedRow = statement.executeUpdate();
			
			ResultSet rs = statement.getGeneratedKeys();

			if(rs.next())
			{
				rowIdOfInsertedRow = rs.getInt(1);
			}
			
			
			
//			System.out.println("Key autogenerated Save Cart: " + rowIdOfInsertedRow);
			
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		finally
		{
			
			try {
			
				if(statement!=null)
				{statement.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
			try {
				
				if(connection!=null)
				{connection.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}

		
		return rowIdOfInsertedRow;
	}
	

	public int updateCart(Cart cart)
	{	
		String updateStatement = "UPDATE " + Cart.TABLE_NAME
				+ " SET "
				+ Cart.END_USER_ID + " = ?,"
				+ Cart.SHOP_ID + " = ?"
				+ " WHERE " + Cart.CART_ID + " = ?";
		
		Connection connection = null;
		PreparedStatement statement = null;
		int updatedRows = -1;
		
		try {
			
			connection = dataSource.getConnection();
			statement = connection.prepareStatement(updateStatement);

			statement.setObject(1,cart.getEndUserID());
			statement.setObject(2,cart.getShopID());

			updatedRows = statement.executeUpdate();
			
			
			System.out.println("Total rows updated: " + updatedRows);	
			
			//conn.close();
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		finally
		
		{
			
			try {
			
				if(statement!=null)
				{statement.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
			try {
				
				if(connection!=null)
				{connection.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}

		return updatedRows;
		
	}
	

	public int deleteCart(int cartID)
	{
		
		String deleteStatement = "DELETE FROM " + Cart.TABLE_NAME
								+ " WHERE " + Cart.CART_ID + " = ?";
		
		
		Connection connection= null;
		PreparedStatement statement = null;
		int rowsCountDeleted = 0;
		try {
			
			connection = dataSource.getConnection();
			statement = connection.prepareStatement(deleteStatement);
			statement.setObject(1,cartID);

			rowsCountDeleted = statement.executeUpdate();
//			System.out.println(" Deleted Count: " + rowsCountDeleted);

			connection.close();
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		finally
		
		{
			
			try {
			
				if(statement!=null)
				{statement.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
			try {
				
				if(connection!=null)
				{connection.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
	
		
		return rowsCountDeleted;
	}



	public int getCartID(Integer endUserID, Integer shopID)
	{

		String query = "SELECT " + Cart.TABLE_NAME + "." + Cart.CART_ID
					+ " FROM " + Cart.TABLE_NAME
					+ " WHERE " + Cart.END_USER_ID + " = " + endUserID
					+ " AND " + Cart.SHOP_ID + " = " + shopID;



		Connection connection = null;
		Statement statement = null;
		ResultSet rs = null;

		try {

			connection = dataSource.getConnection();
			statement = connection.createStatement();

			rs = statement.executeQuery(query);

			if(rs.next())
			{
				return rs.getInt(Cart.CART_ID);
			}



		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		finally
		{

			try {
				if(rs!=null)
				{rs.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}

			try {

				if(statement!=null)
				{statement.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}

			try {

				if(connection!=null)
				{connection.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}


		return 0;
	}



//
//
//	public ArrayList<Cart> readCarts(Integer endUserID, Integer shopID)
//	{
//
//		String query = " SELECT " + Cart.TABLE_NAME + "." + Cart.CART_ID + ","
//									+ Cart.TABLE_NAME + "." + Cart.SHOP_ID + ","
//									+ Cart.TABLE_NAME + "." + Cart.END_USER_ID + ""
//						+ " FROM " + Cart.TABLE_NAME;
//
//
//
//		if(endUserID != null)
//		{
//			query = query + " AND " + Cart.END_USER_ID + " = " + endUserID;
//		}
//
//
//		if(shopID != null)
//		{
//			query = query + " AND " + Cart.SHOP_ID + " = " + shopID;
//		}
//
//
//
//		ArrayList<Cart> cartsList = new ArrayList<Cart>();
//
//		Connection connection = null;
//		Statement statement = null;
//		ResultSet rs = null;
//
//		try {
//
//			connection = dataSource.getConnection();
//			statement = connection.createStatement();
//
//			rs = statement.executeQuery(query);
//
//			while(rs.next())
//			{
//
//				Cart cart = new Cart();
//
//				cart.setCartID(rs.getInt(Cart.CART_ID));
//				cart.setEndUserID(rs.getInt(Cart.END_USER_ID));
//				cart.setShopID(rs.getInt(Cart.SHOP_ID));
//
//				cartsList.add(cart);
//
//			}
//
//
//
//		} catch (SQLException e) {
//			// TODO Auto-generated catch block
//			e.printStackTrace();
//		}
//
//
//		finally
//
//		{
//
//			try {
//					if(rs!=null)
//					{rs.close();}
//				} catch (SQLException e) {
//					// TODO Auto-generated catch block
//					e.printStackTrace();
//				}
//
//			try {
//
//				if(statement!=null)
//				{statement.close();}
//			} catch (SQLException e) {
//				// TODO Auto-generated catch block
//				e.printStackTrace();
//			}
//
//			try {
//
//				if(connection!=null)
//				{connection.close();}
//			} catch (SQLException e) {
//				// TODO Auto-generated catch block
//				e.printStackTrace();
//			}
//		}
//
//
//		return cartsList;
//	}



	
	public Cart readCart(int cartID)
	{
		
		String query = "SELECT " + Cart.TABLE_NAME + "." + Cart.CART_ID + ","
								 + Cart.TABLE_NAME + "." + Cart.SHOP_ID + ","
								 + Cart.TABLE_NAME + "." + Cart.END_USER_ID + ""

					+ " FROM " + Cart.TABLE_NAME
					+ " WHERE " + Cart.CART_ID + " = " + cartID;



		Connection connection = null;
		Statement statement = null;
		ResultSet rs = null;

		Cart cart = null;
		
		try {
			
			connection = dataSource.getConnection();
			statement = connection.createStatement();

			rs = statement.executeQuery(query);
			
			while(rs.next())
			{
				cart = new Cart();
				cart.setCartID(rs.getInt(Cart.CART_ID));
				cart.setShopID(rs.getInt(Cart.SHOP_ID));
				cart.setEndUserID(rs.getInt(Cart.END_USER_ID));
			}
			
			
			//System.out.println("Total itemCategories queried " + itemCategoryList.size());	
	
		
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} finally
		
		{
			
			try {
					if(rs!=null)
					{rs.close();}
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			
			try {
			
				if(statement!=null)
				{statement.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
			try {
				
				if(connection!=null)
				{connection.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
	
		return cart;
	}	
}
